name: pkg
services:

  postgres:
    image: postgres:latest
    hostname: postgres  # Added explicit hostname
    environment:
      - POSTGRES_USER=jasoet
      - POSTGRES_PASSWORD=localhost
      - POSTGRES_DB=pkg_db
    ports:
      - "5439:5432"
    volumes:
      - pg:/var/lib/postgresql/data
      - ./pg/init:/docker-entrypoint-initdb.d
      - ./pg/backup:/var/lib/postgresql/pg-backup
    networks:
      - net

networks:
  net:

volumes:
  pg:
