# Web Service Configuration Template
# This file demonstrates how to configure a web service using github.com/jasoet/pkg

environment: development
debug: true

server:
  port: 8080
  readTimeout: 30s
  writeTimeout: 30s
  shutdownTimeout: 10s
  enableHealthChecks: true
  enableMetrics: true

database:
  dbType: POSTGRES
  host: localhost
  port: 5432
  username: postgres
  password: password
  dbName: myapp
  timeout: 30s
  maxIdleConns: 10
  maxOpenConns: 100
  enableLogging: true

# Optional external API configuration
externalApi:
  baseUrl: https://api.example.com
  timeout: 30s
  retryCount: 3
  apiKey: your-api-key-here

# Optional Redis configuration
redis:
  host: localhost
  port: 6379
  password: ""
  database: 0
  maxRetries: 3
  poolSize: 10