# Docker Compose for web service development
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DEBUG=true
      - APP_DATABASE_HOST=postgres
      - APP_DATABASE_USERNAME=postgres  
      - APP_DATABASE_PASSWORD=password
      - APP_DATABASE_DBNAME=myapp
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config.yaml:/root/config.yaml
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Optional: Database management tool
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge