# CLI Application Configuration Template
# This file demonstrates how to configure a CLI application using github.com/jasoet/pkg

environment: development
debug: true

database:
  dbType: POSTGRES
  host: localhost
  port: 5432
  username: postgres
  password: password
  dbName: cli_app
  timeout: 30s
  maxIdleConns: 5
  maxOpenConns: 25
  enableLogging: true

# Optional external API configuration
externalApi:
  baseUrl: https://api.example.com
  timeout: 30s
  retryCount: 3
  apiKey: ""

# CLI-specific configuration
cli:
  outputFormat: table  # table, json, csv
  dateFormat: "2006-01-02 15:04:05"
  batchSize: 100