name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint & Test
    if: >
      github.event_name == 'push' ||
      github.actor == 'jasoet'
    runs-on: [self-hosted, local, macOS, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint
        run: nix develop --command golangci-lint run ./...

      - name: Test
        run: nix develop --command go test -race -count=1 ./... -tags=!examples
